package soulscorch.scripting.soul;

import Std;
import Math;
import StringTools;

using StringTools;

class SoulScriptParser {
    public static function transpile(source:String):String {
        if (source == null) return "";
        
        var output:Array<String> = [];
        var indent:Int = 0;
        
        output.push("// Generated by SoulScorch Unrestricted Engine Parser");

        for (raw in source.split("\n")) {
            var line:String = raw.replace("\r", "").trim();
            
            // Skip empty lines & comments
            if (line.length == 0 || line.startsWith("#") || line.startsWith("//")) {
                continue;
            }

            // Block closers
            if (line == "end" || line == "}") {
                indent = Std.int(Math.max(0, indent - 1));
                output.push(spaces(indent) + "}");
                continue;
            }

            // 1. Lifecycle & Event Headers
            var header:String = translateHeader(line);
            if (header != null) {
                output.push(spaces(indent) + header);
                indent++;
                continue;
            }

            // 2. Modchart & Strumline Tweens (strumline.player[0].x -> 400 in 0.5s)
            var strumTween:String = translateStrumTween(line);
            if (strumTween != null) {
                output.push(spaces(indent) + strumTween);
                continue;
            }

            // 3. 3D & Vector Tweens (camera3D.position -> [0, 5, 10] in 2.0s)
            var vec3Tween:String = translateVector3Tween(line);
            if (vec3Tween != null) {
                output.push(spaces(indent) + vec3Tween);
                continue;
            }

            // 4. Shader Uniform Tweens (shader.vhs.chromaticAmount -> 0.05 in 0.3s (cubeOut))
            var shaderTween:String = translateShaderTween(line);
            if (shaderTween != null) {
                output.push(spaces(indent) + shaderTween);
                continue;
            }

            // 5. Standard Scalar Tweens (target.prop -> val in Xs (ease))
            var tween:String = translateTween(line);
            if (tween != null) {
                output.push(spaces(indent) + tween);
                continue;
            }

            // 6. Macro Commands (Noteskins, Events, Particles, 3D, Shaders, States, Stages, Stems)
            var macroLine:String = translateMacros(line);
            if (macroLine != null) {
                output.push(spaces(indent) + macroLine);
                continue;
            }

            // 7. Default HScript passthrough
            output.push(spaces(indent) + line);
        }

        // Close any unclosed indentation blocks at EOF
        while (indent-- > 0) {
            output.push("}");
        }

        return output.join("\n");
    }

    private static function translateHeader(line:String):String {
        // --- Timing Triggers ---
        var atBeat:EReg = ~/^at beat (-?\d+(?:\.\d+)?)\s*:/i;
        if (atBeat.match(line)) return "if (curBeat == " + atBeat.matched(1) + ") {";

        var everyBeat:EReg = ~/^every (\d+(?:\.\d+)?) beats\s*:/i;
        if (everyBeat.match(line)) return "if (curBeat % " + everyBeat.matched(1) + " == 0) {";

        var atStep:EReg = ~/^at step (-?\d+(?:\.\d+)?)\s*:/i;
        if (atStep.match(line)) return "if (curStep == " + atStep.matched(1) + ") {";

        var everyStep:EReg = ~/^every (\d+(?:\.\d+)?) steps\s*:/i;
        if (everyStep.match(line)) return "if (curStep % " + everyStep.matched(1) + " == 0) {";

        // --- Song Chart Events ---
        var sEvent:EReg = ~/^on songEvent\("([^"]+)"(?:,\s*([A-Za-z0-9_]+))?(?:,\s*([A-Za-z0-9_]+))?\)\s*:/i;
        if (sEvent.match(line)) {
            var name = sEvent.matched(1);
            var v1 = sEvent.matched(2) != null ? sEvent.matched(2) : "value1";
            var v2 = sEvent.matched(3) != null ? sEvent.matched(3) : "value2";
            return 'if (eventName == "$name") { var $v1 = eventVal1; var $v2 = eventVal2;';
        }

        // --- Core Lifecycle ---
        if (~/^on (create|onCreate)\s*:/i.match(line)) return "function create() {";
        if (~/^on (postCreate|onPostCreate)\s*:/i.match(line)) return "function postCreate() {";
        if (~/^on (update|onUpdate)\s*:/i.match(line)) return "function update(elapsed) {";
        if (~/^on (updatePost|onUpdatePost)\s*:/i.match(line)) return "function updatePost(elapsed) {";
        if (~/^on (beatHit|onBeatHit)\s*:/i.match(line)) return "function onBeatHit(curBeat) {";
        if (~/^on (stepHit|onStepHit)\s*:/i.match(line)) return "function onStepHit(curStep) {";
        if (~/^on (destroy|onDestroy)\s*:/i.match(line)) return "function destroy() {";
        
        // --- State & Scene Lifecycle ---
        if (~/^on preStateSwitch\s*:/i.match(line)) return "function preStateSwitch() {";
        if (~/^on postStateSwitch\s*:/i.match(line)) return "function postStateSwitch() {";
        if (~/^on stageReady\s*:/i.match(line)) return "function onStageReady() {";
        if (~/^on 3dReady\s*:/i.match(line)) return "function on3DReady() {";

        // --- Note Hit & Miss Hooks ---
        var noteHit:EReg = ~/^on noteHit\((.*)\)\s*:/i;
        if (noteHit.match(line)) return 'if (event == "noteHit" && (' + noteHit.matched(1) + ')) {';

        var noteMiss:EReg = ~/^on noteMiss\((.*)\)\s*:/i;
        if (noteMiss.match(line)) return 'if (event == "noteMiss" && (' + noteMiss.matched(1) + ')) {';

        var evt:EReg = ~/^on event\("([^"]+)"\)\s*:/i;
        if (evt.match(line)) return 'if (eventName == "' + evt.matched(1) + '") {';

        return null;
    }

    private static function translateStrumTween(line:String):String {
        var reg:EReg = ~/^strumline\.(player|opponent)\[([0-3])\]\.([A-Za-z0-9_]+)\s*->\s*(.*?)\s+in\s+([0-9.]+)s?(?:\s*\(([^)]+)\))?;?$/i;
        if (!reg.match(line)) return null;

        var group = reg.matched(1) == "player" ? "game.playerStrums" : "game.opponentStrums";
        var idx = reg.matched(2);
        var prop = reg.matched(3);
        var val = reg.matched(4);
        var dur = reg.matched(5);
        var ease = reg.matched(6) != null ? reg.matched(6) : "linear";

        return 'FlxTween.tween($group.members[$idx], {$prop: $val}, $dur, {ease: FlxEase.$ease});';
    }

    private static function translateTween(line:String):String {
        var regex:EReg = ~/^([A-Za-z_][A-Za-z0-9_.]*)\.([A-Za-z_][A-Za-z0-9_]*)\s*->\s*(.*?)\s+in\s+([0-9.]+)s?(?:\s*\(([^)]+)\))?;?$/;
        if (!regex.match(line)) return null;

        var target:String = regex.matched(1);
        var prop:String = regex.matched(2);
        var value:String = regex.matched(3);
        var dur:String = regex.matched(4);
        var ease:String = regex.matched(5) != null ? regex.matched(5) : "linear";

        return 'FlxTween.tween(' + target + ', {' + prop + ': ' + value + '}, ' + dur + ', {ease: FlxEase.' + ease + '});';
    }

    private static function translateVector3Tween(line:String):String {
        var regex:EReg = ~/^([A-Za-z_][A-Za-z0-9_.]*)\.(position|target|rotation|scale)\s*->\s*\[\s*(-?[0-9.]+)\s*,\s*(-?[0-9.]+)\s*,\s*(-?[0-9.]+)\s*\]\s+in\s+([0-9.]+)s?(?:\s*\(([^)]+)\))?;?$/;
        if (!regex.match(line)) return null;

        var target = regex.matched(1);
        var prop = regex.matched(2);
        var x = regex.matched(3);
        var y = regex.matched(4);
        var z = regex.matched(5);
        var dur = regex.matched(6);
        var ease = regex.matched(7) != null ? regex.matched(7) : "linear";

        return 'FlxTween.tween(' + target + '.' + prop + ', {x: ' + x + ', y: ' + y + ', z: ' + z + '}, ' + dur + ', {ease: FlxEase.' + ease + '});';
    }

    private static function translateShaderTween(line:String):String {
        var regex:EReg = ~/^shader\.([A-Za-z0-9_]+)\.([A-Za-z0-9_]+)\s*->\s*([0-9.]+)\s+in\s+([0-9.]+)s?(?:\s*\(([^)]+)\))?;?$/;
        if (!regex.match(line)) return null;

        var shaderVar = regex.matched(1);
        var uniform = regex.matched(2);
        var targetVal = regex.matched(3);
        var dur = regex.matched(4);
        var ease = regex.matched(5) != null ? regex.matched(5) : "linear";

        return 'FlxTween.num(' + shaderVar + '.getFloat("' + uniform + '"), ' + targetVal + ', ' + dur + ', {ease: FlxEase.' + ease + '}, function(v) { ' + shaderVar + '.setFloat("' + uniform + '", v); });';
    }

    private static function translateMacros(line:String):String {
        // --- 1. Custom Noteskins & Splashes ---
        var nsAll:EReg = ~/^noteskin\.set\("([^"]+)"\);?$/i;
        if (nsAll.match(line)) return 'game.changeNoteSkin("' + nsAll.matched(1) + '");';

        var nsPlayer:EReg = ~/^noteskin\.setPlayer\("([^"]+)"\);?$/i;
        if (nsPlayer.match(line)) return 'game.changePlayerNoteSkin("' + nsPlayer.matched(1) + '");';

        var splash:EReg = ~/^noteskin\.setSplash\("([^"]+)"\);?$/i;
        if (splash.match(line)) return 'game.changeSplashSkin("' + splash.matched(1) + '");';

        // --- 2. GPU Particles & VFX ---
        var part:EReg = ~/^spawnParticles\("([^"]+)",\s*\[\s*(-?[0-9.]+)\s*,\s*(-?[0-9.]+)\s*\](?:,\s*([0-9]+))?\);?$/i;
        if (part.match(line)) {
            var count = part.matched(4) != null ? part.matched(4) : "20";
            return 'game.particleManager.spawn("' + part.matched(1) + '", ' + part.matched(2) + ', ' + part.matched(3) + ', ' + count + ');';
        }

        // --- 3. 3D Model Skeletal Animation ---
        var mAnim:EReg = ~/^model\("([^"]+)"\)\.playAnim\("([^"]+)"(?:,\s*(true|false))?\);?$/i;
        if (mAnim.match(line)) {
            var loop = mAnim.matched(3) != null ? mAnim.matched(3) : "false";
            return 'game.scene3D.getMesh("' + mAnim.matched(1) + '").playAnim("' + mAnim.matched(2) + '", ' + loop + ');';
        }

        // --- 4. Character Animation Overrides ---
        var cAnim:EReg = ~/^character\("(boyfriend|dad|gf)"\)\.playAnim\("([^"]+)"(?:,\s*(true|false))?\);?$/i;
        if (cAnim.match(line)) {
            var targetChar = cAnim.matched(1) == "boyfriend" ? "game.boyfriend" : (cAnim.matched(1) == "dad" ? "game.dad" : "game.gf");
            var forced = cAnim.matched(3) != null ? cAnim.matched(3) : "true";
            return targetChar + '.playAnim("' + cAnim.matched(2) + '", ' + forced + ');';
        }

        // --- 5. State & SubState Navigation ---
        var switchSt:EReg = ~/^switchState\("([^"]+)"\);?$/i;
        if (switchSt.match(line)) return 'FlxG.switchState(new ScriptedState(Paths.script("states/' + switchSt.matched(1) + '")));';

        var openSub:EReg = ~/^openSubState\("([^"]+)"(?:,\s*([0-9.]+))?\);?$/i;
        if (openSub.match(line)) {
            var bg = openSub.matched(2) != null ? openSub.matched(2) : "0.6";
            return 'FlxG.state.openSubState(new ScriptedSubState(Paths.script("states/' + openSub.matched(1) + '"), ' + bg + '));';
        }

        if (~/^closeSubState\(\);?$/i.match(line)) return 'close();';

        // --- 6. 3D Engine Macros ---
        var load3DSt:EReg = ~/^load3DStage\("([^"]+)"\);?$/i;
        if (load3DSt.match(line)) return 'soulscorch.threed.Stage3DLoader.loadStage(Paths.file("' + load3DSt.matched(1) + '"), game.scene3D);';

        var loadMdl:EReg = ~/^loadModel\("([^"]+)",\s*"([^"]+)"(?:,\s*\[\s*(-?[0-9.]+)\s*,\s*(-?[0-9.]+)\s*,\s*(-?[0-9.]+)\s*\])?\);?$/i;
        if (loadMdl.match(line)) {
            var id = loadMdl.matched(1);
            var path = loadMdl.matched(2);
            var x = loadMdl.matched(3) != null ? loadMdl.matched(3) : "0";
            var y = loadMdl.matched(4) != null ? loadMdl.matched(4) : "0";
            var z = loadMdl.matched(5) != null ? loadMdl.matched(5) : "0";
            return 'var _mesh = soulscorch.threed.ModelLoader.load(Paths.file("' + path + '")); _mesh.position.set(' + x + ', ' + y + ', ' + z + '); game.scene3D.addMesh("' + id + '", _mesh);';
        }

        var fov:EReg = ~/^camera3D\.fov\s*->\s*([0-9.]+)\s+in\s+([0-9.]+)s?(?:\s*\(([^)]+)\))?;?$/i;
        if (fov.match(line)) {
            var targetFov = fov.matched(1);
            var dur = fov.matched(2);
            var ease = fov.matched(3) != null ? fov.matched(3) : "linear";
            return 'FlxTween.tween(game.scene3D.camera, {fov: ' + targetFov + '}, ' + dur + ', {ease: FlxEase.' + ease + '});';
        }

        // --- 7. Shaders & Filters ---
        var addShd:EReg = ~/^addShader\("([^"]+)"(?:,\s*"([^"]+)")?\);?$/i;
        if (addShd.match(line)) {
            var sName = addShd.matched(1);
            var targetCam = addShd.matched(2) != null ? addShd.matched(2) : "FlxG.camera";
            return 'var ' + sName + ' = new SoulShader("' + sName + '"); ' + targetCam + '.setFilters([new ShaderFilter(' + sName + ')]);';
        }

        var rmShd:EReg = ~/^removeShaders\((?:["']?([^"']*)["']?)?\);?$/i;
        if (rmShd.match(line)) {
            var cam = (rmShd.matched(1) != null && rmShd.matched(1).length > 0) ? rmShd.matched(1) : "FlxG.camera";
            return cam + '.setFilters([]);';
        }

        // --- 8. Audio Stems & Dynamic DSP ---
        var stmVol:EReg = ~/^stems\.setVolume\("([^"]+)",\s*([0-9.]+)\);?$/i;
        if (stmVol.match(line)) return 'game.stemMixer.setVolume("' + stmVol.matched(1) + '", ' + stmVol.matched(2) + ');';

        var stmMute:EReg = ~/^stems\.mute\("([^"]+)"\);?$/i;
        if (stmMute.match(line)) return 'game.stemMixer.setVolume("' + stmMute.matched(1) + '", 0.0);';

        // --- 9. Camera & Screen Basics ---
        var shake:EReg = ~/^screen\.shake\(([0-9.]+),\s*([0-9.]+)s?\);?$/i;
        if (shake.match(line)) return 'FlxG.camera.shake(' + shake.matched(1) + ', ' + shake.matched(2) + ');';

        var bump:EReg = ~/^camera\.bump\(([0-9.]+)\);?$/i;
        if (bump.match(line)) return 'FlxG.camera.zoom += ' + bump.matched(1) + ';';

        var snd:EReg = ~/^playSound\("([^"]+)"(?:,\s*([0-9.]+))?\);?$/i;
        if (snd.match(line)) {
            var vol = snd.matched(2) != null ? snd.matched(2) : "1.0";
            return 'FlxG.sound.play(Paths.sound("' + snd.matched(1) + '"), ' + vol + ');';
        }

        return null;
    }

    private static function spaces(count:Int):String {
        var result:String = "";
        for (i in 0...count) result += "    ";
        return result;
    }
}