name: Release Archives (Full Game)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: windows
            archive_name: SoulScorch-Windows-Full.zip
            source_dir: bin/windows/bin
          - os: ubuntu-latest
            target: linux
            archive_name: SoulScorch-Linux-Full.tar.gz
            source_dir: bin/linux/bin
          - os: macos-14
            target: mac
            archive_name: SoulScorch-Mac-Full.zip
            source_dir: bin/mac/bin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4

      - name: Setup Haxelib (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          haxelib setup C:/haxelib
          haxelib install lime 8.1.2 --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.5.0 --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install hxcpp 4.3.2 --quiet
          haxelib install hxdiscord_rpc --quiet
          haxelib run lime setup -y

      - name: Setup Haxelib (Unix / Linux / macOS)
        if: matrix.os != 'windows-latest'
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.2 --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.5.0 --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install hxcpp 4.3.2 --quiet
          haxelib install hxdiscord_rpc --quiet
          haxelib run lime setup -y

      - name: Build Engine
        run: haxelib run lime build ${{ matrix.target }} -release
        env:
          HXCPP_COMPILE_THREADS: 8

      - name: Package Windows / Mac Archive
        if: matrix.os != 'ubuntu-latest'
        shell: bash
        run: |
          cd ${{ matrix.source_dir }}
          zip -r ../../../${{ matrix.archive_name }} .

      - name: Package Linux Archive
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd ${{ matrix.source_dir }}
          tar -czf ../../../${{ matrix.archive_name }} .

      - name: Upload Full Release Archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive_name }}
          path: ${{ matrix.archive_name }}